storage:
  storage_type: REDIS
  storage_params:
    host: "localhost"
    port: 6379
    username: ""
    password: ""
metric_sources:
  - metric_source_type: PROMETHEUS
    metric_source_params:
      prometheus_url: "http://localhost:9090"
      timeout: 20
alerter:
  alerter_type: "PROMETHEUS_ALERT_MANAGER"
  alerter_params:
    url: "http://localhost:9093"
rules:
  # - id: test-rule-1
  #   metric_source_type: PROMETHEUS
  #   model_type: dummy
  #   model_params:
  #     anomaly_count: 3
  #   query: "promhttp_metric_handler_requests_total"
  #   alias_by_label_values:
  #     - "__name__"
  #     - "code"
  #     - "job"
  #   # TODO: allow expand label and annotation values with label value of metric.
  #   labels:
  #     test: alert
  #   annotations:
  #     description: test alerting rule
  - id: test-holes-rule-1
    metric_source_type: PROMETHEUS
    model_type: "voting_of_3_models_with_2_seq"
    query: "dummy_observable_app_metric_with_holes"
    # TODO: allow expand label and annotation values with label value of metric.
    labels:
      test: alert
    annotations:
      description: test alerting rule