services:
  redis:
    image: redis:6.2.12-alpine3.18
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:v3.6.0
    ports:
      - "9090:9090"

volumes:
  data: