services:
  redis:
    image: redis:6.2.12-alpine3.18
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:v3.6.0
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.30.1
    ports:
      - "9093:9093"
    volumes:
      - ./local/alertmanager/:/etc/alertmanager/
    command:
      - --config.file=/etc/alertmanager/alertmanager.yaml
      - --enable-feature=utf8-strict-mode
      - --log.level=debug
    

volumes:
  data: